/**
 * Canonical ISO 3166-1 alpha-2 country dataset for the seed pipeline.
 *
 * This is the single source of truth the generator turns into the
 * `public.countries` INSERTs in the Phase 1 migration. Every value was
 * validated by findEncodingCorruption() before commit; the regression
 * suite re-runs that check and byte-compares generator output against the
 * committed migration, so mojibake and drift both fail loudly.
 *
 * Generated once from the repaired Phase 1 seed (see docs/development/
 * global-identity.md, "Country seed pipeline"). Do not hand-edit names;
 * regenerate with: npm run countries:generate
 */

export interface CountrySeedRow {
  code: string;
  name: string;
  default_currency: string;
  default_locale: string;
  calling_code: string | null;
  active: boolean;
}

export const COUNTRY_SEED: CountrySeedRow[] = [
  { code: "AD", name: "Andorra", default_currency: "EUR", default_locale: "ca-AD", calling_code: "+376", active: true },
  { code: "AE", name: "United Arab Emirates", default_currency: "AED", default_locale: "ar-AE", calling_code: "+971", active: true },
  { code: "AF", name: "Afghanistan", default_currency: "AFN", default_locale: "ps-AF", calling_code: "+93", active: true },
  { code: "AG", name: "Antigua and Barbuda", default_currency: "XCD", default_locale: "en-AG", calling_code: "+1268", active: true },
  { code: "AI", name: "Anguilla", default_currency: "XCD", default_locale: "en-AI", calling_code: "+1264", active: true },
  { code: "AL", name: "Albania", default_currency: "ALL", default_locale: "sq-AL", calling_code: "+355", active: true },
  { code: "AM", name: "Armenia", default_currency: "AMD", default_locale: "hy-AM", calling_code: "+374", active: true },
  { code: "AO", name: "Angola", default_currency: "AOA", default_locale: "pt-AO", calling_code: "+244", active: true },
  { code: "AQ", name: "Antarctica", default_currency: "USD", default_locale: "en-AQ", calling_code: null, active: false },
  { code: "AR", name: "Argentina", default_currency: "ARS", default_locale: "es-AR", calling_code: "+54", active: true },
  { code: "AS", name: "American Samoa", default_currency: "USD", default_locale: "en-AS", calling_code: "+1684", active: true },
  { code: "AT", name: "Austria", default_currency: "EUR", default_locale: "de-AT", calling_code: "+43", active: true },
  { code: "AU", name: "Australia", default_currency: "AUD", default_locale: "en-AU", calling_code: "+61", active: true },
  { code: "AW", name: "Aruba", default_currency: "AWG", default_locale: "nl-AW", calling_code: "+297", active: true },
  { code: "AX", name: "Åland Islands", default_currency: "EUR", default_locale: "sv-AX", calling_code: "+358", active: false },
  { code: "AZ", name: "Azerbaijan", default_currency: "AZN", default_locale: "az-AZ", calling_code: "+994", active: true },
  { code: "BA", name: "Bosnia and Herzegovina", default_currency: "BAM", default_locale: "bs-BA", calling_code: "+387", active: true },
  { code: "BB", name: "Barbados", default_currency: "BBD", default_locale: "en-BB", calling_code: "+1246", active: true },
  { code: "BD", name: "Bangladesh", default_currency: "BDT", default_locale: "bn-BD", calling_code: "+880", active: true },
  { code: "BE", name: "Belgium", default_currency: "EUR", default_locale: "nl-BE", calling_code: "+32", active: true },
  { code: "BF", name: "Burkina Faso", default_currency: "XOF", default_locale: "fr-BF", calling_code: "+226", active: true },
  { code: "BG", name: "Bulgaria", default_currency: "EUR", default_locale: "bg-BG", calling_code: "+359", active: true },
  { code: "BH", name: "Bahrain", default_currency: "BHD", default_locale: "ar-BH", calling_code: "+973", active: true },
  { code: "BI", name: "Burundi", default_currency: "BIF", default_locale: "fr-BI", calling_code: "+257", active: true },
  { code: "BJ", name: "Benin", default_currency: "XOF", default_locale: "fr-BJ", calling_code: "+229", active: true },
  { code: "BL", name: "Saint Barthélemy", default_currency: "EUR", default_locale: "fr-BL", calling_code: "+590", active: false },
  { code: "BM", name: "Bermuda", default_currency: "BMD", default_locale: "en-BM", calling_code: "+1441", active: true },
  { code: "BN", name: "Brunei", default_currency: "BND", default_locale: "ms-BN", calling_code: "+673", active: true },
  { code: "BO", name: "Bolivia", default_currency: "BOB", default_locale: "es-BO", calling_code: "+591", active: true },
  { code: "BQ", name: "Caribbean Netherlands", default_currency: "USD", default_locale: "en-BQ", calling_code: "+599", active: true },
  { code: "BR", name: "Brazil", default_currency: "BRL", default_locale: "pt-BR", calling_code: "+55", active: true },
  { code: "BS", name: "Bahamas", default_currency: "BSD", default_locale: "en-BS", calling_code: "+1242", active: true },
  { code: "BT", name: "Bhutan", default_currency: "BTN", default_locale: "dz-BT", calling_code: "+975", active: true },
  { code: "BV", name: "Bouvet Island", default_currency: "NOK", default_locale: "no-BV", calling_code: "+47", active: false },
  { code: "BW", name: "Botswana", default_currency: "BWP", default_locale: "en-BW", calling_code: "+267", active: true },
  { code: "BY", name: "Belarus", default_currency: "BYN", default_locale: "be-BY", calling_code: "+375", active: true },
  { code: "BZ", name: "Belize", default_currency: "BZD", default_locale: "en-BZ", calling_code: "+501", active: true },
  { code: "CA", name: "Canada", default_currency: "CAD", default_locale: "en-CA", calling_code: "+1", active: true },
  { code: "CC", name: "Cocos (Keeling) Islands", default_currency: "AUD", default_locale: "en-CC", calling_code: "+61", active: true },
  { code: "CD", name: "DR Congo", default_currency: "CDF", default_locale: "fr-CD", calling_code: "+243", active: true },
  { code: "CF", name: "Central African Republic", default_currency: "XAF", default_locale: "fr-CF", calling_code: "+236", active: true },
  { code: "CG", name: "Congo", default_currency: "XAF", default_locale: "fr-CG", calling_code: "+242", active: true },
  { code: "CH", name: "Switzerland", default_currency: "CHF", default_locale: "de-CH", calling_code: "+41", active: true },
  { code: "CI", name: "Ivory Coast", default_currency: "XOF", default_locale: "fr-CI", calling_code: "+225", active: true },
  { code: "CK", name: "Cook Islands", default_currency: "NZD", default_locale: "en-CK", calling_code: "+682", active: true },
  { code: "CL", name: "Chile", default_currency: "CLP", default_locale: "es-CL", calling_code: "+56", active: true },
  { code: "CM", name: "Cameroon", default_currency: "XAF", default_locale: "fr-CM", calling_code: "+237", active: true },
  { code: "CN", name: "China", default_currency: "CNY", default_locale: "zh-CN", calling_code: "+86", active: true },
  { code: "CO", name: "Colombia", default_currency: "COP", default_locale: "es-CO", calling_code: "+57", active: true },
  { code: "CR", name: "Costa Rica", default_currency: "CRC", default_locale: "es-CR", calling_code: "+506", active: true },
  { code: "CU", name: "Cuba", default_currency: "CUP", default_locale: "es-CU", calling_code: "+53", active: true },
  { code: "CV", name: "Cape Verde", default_currency: "CVE", default_locale: "pt-CV", calling_code: "+238", active: true },
  { code: "CW", name: "Curaçao", default_currency: "ANG", default_locale: "en-CW", calling_code: "+599", active: false },
  { code: "CX", name: "Christmas Island", default_currency: "AUD", default_locale: "en-CX", calling_code: "+61", active: true },
  { code: "CY", name: "Cyprus", default_currency: "EUR", default_locale: "el-CY", calling_code: "+357", active: true },
  { code: "CZ", name: "Czechia", default_currency: "CZK", default_locale: "cs-CZ", calling_code: "+420", active: true },
  { code: "DE", name: "Germany", default_currency: "EUR", default_locale: "de-DE", calling_code: "+49", active: true },
  { code: "DJ", name: "Djibouti", default_currency: "DJF", default_locale: "ar-DJ", calling_code: "+253", active: true },
  { code: "DK", name: "Denmark", default_currency: "DKK", default_locale: "da-DK", calling_code: "+45", active: true },
  { code: "DM", name: "Dominica", default_currency: "XCD", default_locale: "en-DM", calling_code: "+1767", active: true },
  { code: "DO", name: "Dominican Republic", default_currency: "DOP", default_locale: "es-DO", calling_code: "+1", active: true },
  { code: "DZ", name: "Algeria", default_currency: "DZD", default_locale: "ar-DZ", calling_code: "+213", active: true },
  { code: "EC", name: "Ecuador", default_currency: "USD", default_locale: "es-EC", calling_code: "+593", active: true },
  { code: "EE", name: "Estonia", default_currency: "EUR", default_locale: "et-EE", calling_code: "+372", active: true },
  { code: "EG", name: "Egypt", default_currency: "EGP", default_locale: "ar-EG", calling_code: "+20", active: true },
  { code: "EH", name: "Western Sahara", default_currency: "MAD", default_locale: "ar-EH", calling_code: "+212", active: true },
  { code: "ER", name: "Eritrea", default_currency: "ERN", default_locale: "ar-ER", calling_code: "+291", active: true },
  { code: "ES", name: "Spain", default_currency: "EUR", default_locale: "es-ES", calling_code: "+34", active: true },
  { code: "ET", name: "Ethiopia", default_currency: "ETB", default_locale: "am-ET", calling_code: "+251", active: true },
  { code: "FI", name: "Finland", default_currency: "EUR", default_locale: "fi-FI", calling_code: "+358", active: true },
  { code: "FJ", name: "Fiji", default_currency: "FJD", default_locale: "en-FJ", calling_code: "+679", active: true },
  { code: "FK", name: "Falkland Islands", default_currency: "FKP", default_locale: "en-FK", calling_code: "+500", active: true },
  { code: "FM", name: "Micronesia", default_currency: "USD", default_locale: "en-FM", calling_code: "+691", active: true },
  { code: "FO", name: "Faroe Islands", default_currency: "DKK", default_locale: "da-FO", calling_code: "+298", active: true },
  { code: "FR", name: "France", default_currency: "EUR", default_locale: "fr-FR", calling_code: "+33", active: true },
  { code: "GA", name: "Gabon", default_currency: "XAF", default_locale: "fr-GA", calling_code: "+241", active: true },
  { code: "GB", name: "United Kingdom", default_currency: "GBP", default_locale: "en-GB", calling_code: "+44", active: true },
  { code: "GD", name: "Grenada", default_currency: "XCD", default_locale: "en-GD", calling_code: "+1473", active: true },
  { code: "GE", name: "Georgia", default_currency: "GEL", default_locale: "ka-GE", calling_code: "+995", active: true },
  { code: "GF", name: "French Guiana", default_currency: "EUR", default_locale: "fr-GF", calling_code: "+594", active: true },
  { code: "GG", name: "Guernsey", default_currency: "GBP", default_locale: "en-GG", calling_code: "+44", active: true },
  { code: "GH", name: "Ghana", default_currency: "GHS", default_locale: "en-GH", calling_code: "+233", active: true },
  { code: "GI", name: "Gibraltar", default_currency: "GIP", default_locale: "en-GI", calling_code: "+350", active: true },
  { code: "GL", name: "Greenland", default_currency: "DKK", default_locale: "kl-GL", calling_code: "+299", active: true },
  { code: "GM", name: "Gambia", default_currency: "GMD", default_locale: "en-GM", calling_code: "+220", active: true },
  { code: "GN", name: "Guinea", default_currency: "GNF", default_locale: "fr-GN", calling_code: "+224", active: true },
  { code: "GP", name: "Guadeloupe", default_currency: "EUR", default_locale: "fr-GP", calling_code: "+590", active: true },
  { code: "GQ", name: "Equatorial Guinea", default_currency: "XAF", default_locale: "es-GQ", calling_code: "+240", active: true },
  { code: "GR", name: "Greece", default_currency: "EUR", default_locale: "el-GR", calling_code: "+30", active: true },
  { code: "GS", name: "South Georgia", default_currency: "SHP", default_locale: "en-GS", calling_code: "+500", active: true },
  { code: "GT", name: "Guatemala", default_currency: "GTQ", default_locale: "es-GT", calling_code: "+502", active: true },
  { code: "GU", name: "Guam", default_currency: "USD", default_locale: "en-GU", calling_code: "+1671", active: true },
  { code: "GW", name: "Guinea-Bissau", default_currency: "XOF", default_locale: "pt-GW", calling_code: "+245", active: true },
  { code: "GY", name: "Guyana", default_currency: "GYD", default_locale: "en-GY", calling_code: "+592", active: true },
  { code: "HK", name: "Hong Kong", default_currency: "HKD", default_locale: "zh-HK", calling_code: "+852", active: true },
  { code: "HM", name: "Heard Island and McDonald Islands", default_currency: "AUD", default_locale: "en-HM", calling_code: null, active: false },
  { code: "HN", name: "Honduras", default_currency: "HNL", default_locale: "es-HN", calling_code: "+504", active: true },
  { code: "HR", name: "Croatia", default_currency: "EUR", default_locale: "hr-HR", calling_code: "+385", active: true },
  { code: "HT", name: "Haiti", default_currency: "HTG", default_locale: "fr-HT", calling_code: "+509", active: true },
  { code: "HU", name: "Hungary", default_currency: "HUF", default_locale: "hu-HU", calling_code: "+36", active: true },
  { code: "ID", name: "Indonesia", default_currency: "IDR", default_locale: "id-ID", calling_code: "+62", active: true },
  { code: "IE", name: "Ireland", default_currency: "EUR", default_locale: "en-IE", calling_code: "+353", active: true },
  { code: "IL", name: "Israel", default_currency: "ILS", default_locale: "he-IL", calling_code: "+972", active: true },
  { code: "IM", name: "Isle of Man", default_currency: "GBP", default_locale: "en-IM", calling_code: "+44", active: true },
  { code: "IN", name: "India", default_currency: "INR", default_locale: "en-IN", calling_code: "+91", active: true },
  { code: "IO", name: "British Indian Ocean Territory", default_currency: "USD", default_locale: "en-IO", calling_code: "+246", active: true },
  { code: "IQ", name: "Iraq", default_currency: "IQD", default_locale: "ar-IQ", calling_code: "+964", active: true },
  { code: "IR", name: "Iran", default_currency: "IRR", default_locale: "fa-IR", calling_code: "+98", active: true },
  { code: "IS", name: "Iceland", default_currency: "ISK", default_locale: "is-IS", calling_code: "+354", active: true },
  { code: "IT", name: "Italy", default_currency: "EUR", default_locale: "it-IT", calling_code: "+39", active: true },
  { code: "JE", name: "Jersey", default_currency: "GBP", default_locale: "en-JE", calling_code: "+44", active: true },
  { code: "JM", name: "Jamaica", default_currency: "JMD", default_locale: "en-JM", calling_code: "+1876", active: true },
  { code: "JO", name: "Jordan", default_currency: "JOD", default_locale: "ar-JO", calling_code: "+962", active: true },
  { code: "JP", name: "Japan", default_currency: "JPY", default_locale: "ja-JP", calling_code: "+81", active: true },
  { code: "KE", name: "Kenya", default_currency: "KES", default_locale: "en-KE", calling_code: "+254", active: true },
  { code: "KG", name: "Kyrgyzstan", default_currency: "KGS", default_locale: "ky-KG", calling_code: "+996", active: true },
  { code: "KH", name: "Cambodia", default_currency: "KHR", default_locale: "km-KH", calling_code: "+855", active: true },
  { code: "KI", name: "Kiribati", default_currency: "AUD", default_locale: "en-KI", calling_code: "+686", active: true },
  { code: "KM", name: "Comoros", default_currency: "KMF", default_locale: "ar-KM", calling_code: "+269", active: true },
  { code: "KN", name: "Saint Kitts and Nevis", default_currency: "XCD", default_locale: "en-KN", calling_code: "+1869", active: true },
  { code: "KP", name: "North Korea", default_currency: "KPW", default_locale: "ko-KP", calling_code: "+850", active: true },
  { code: "KR", name: "South Korea", default_currency: "KRW", default_locale: "ko-KR", calling_code: "+82", active: true },
  { code: "KW", name: "Kuwait", default_currency: "KWD", default_locale: "ar-KW", calling_code: "+965", active: true },
  { code: "KY", name: "Cayman Islands", default_currency: "KYD", default_locale: "en-KY", calling_code: "+1345", active: true },
  { code: "KZ", name: "Kazakhstan", default_currency: "KZT", default_locale: "kk-KZ", calling_code: "+7", active: true },
  { code: "LA", name: "Laos", default_currency: "LAK", default_locale: "lo-LA", calling_code: "+856", active: true },
  { code: "LB", name: "Lebanon", default_currency: "LBP", default_locale: "ar-LB", calling_code: "+961", active: true },
  { code: "LC", name: "Saint Lucia", default_currency: "XCD", default_locale: "en-LC", calling_code: "+1758", active: true },
  { code: "LI", name: "Liechtenstein", default_currency: "CHF", default_locale: "de-LI", calling_code: "+423", active: true },
  { code: "LK", name: "Sri Lanka", default_currency: "LKR", default_locale: "si-LK", calling_code: "+94", active: true },
  { code: "LR", name: "Liberia", default_currency: "LRD", default_locale: "en-LR", calling_code: "+231", active: true },
  { code: "LS", name: "Lesotho", default_currency: "LSL", default_locale: "en-LS", calling_code: "+266", active: true },
  { code: "LT", name: "Lithuania", default_currency: "EUR", default_locale: "lt-LT", calling_code: "+370", active: true },
  { code: "LU", name: "Luxembourg", default_currency: "EUR", default_locale: "de-LU", calling_code: "+352", active: true },
  { code: "LV", name: "Latvia", default_currency: "EUR", default_locale: "lv-LV", calling_code: "+371", active: true },
  { code: "LY", name: "Libya", default_currency: "LYD", default_locale: "ar-LY", calling_code: "+218", active: true },
  { code: "MA", name: "Morocco", default_currency: "MAD", default_locale: "ar-MA", calling_code: "+212", active: true },
  { code: "MC", name: "Monaco", default_currency: "EUR", default_locale: "fr-MC", calling_code: "+377", active: true },
  { code: "MD", name: "Moldova", default_currency: "MDL", default_locale: "ro-MD", calling_code: "+373", active: true },
  { code: "ME", name: "Montenegro", default_currency: "EUR", default_locale: "cnr-ME", calling_code: "+382", active: true },
  { code: "MF", name: "Saint Martin", default_currency: "EUR", default_locale: "fr-MF", calling_code: "+590", active: true },
  { code: "MG", name: "Madagascar", default_currency: "MGA", default_locale: "fr-MG", calling_code: "+261", active: true },
  { code: "MH", name: "Marshall Islands", default_currency: "USD", default_locale: "en-MH", calling_code: "+692", active: true },
  { code: "MK", name: "North Macedonia", default_currency: "MKD", default_locale: "mk-MK", calling_code: "+389", active: true },
  { code: "ML", name: "Mali", default_currency: "XOF", default_locale: "fr-ML", calling_code: "+223", active: true },
  { code: "MM", name: "Myanmar", default_currency: "MMK", default_locale: "my-MM", calling_code: "+95", active: true },
  { code: "MN", name: "Mongolia", default_currency: "MNT", default_locale: "mn-MN", calling_code: "+976", active: true },
  { code: "MO", name: "Macau", default_currency: "MOP", default_locale: "zh-MO", calling_code: "+853", active: true },
  { code: "MP", name: "Northern Mariana Islands", default_currency: "USD", default_locale: "en-MP", calling_code: "+1670", active: true },
  { code: "MQ", name: "Martinique", default_currency: "EUR", default_locale: "fr-MQ", calling_code: "+596", active: true },
  { code: "MR", name: "Mauritania", default_currency: "MRU", default_locale: "ar-MR", calling_code: "+222", active: true },
  { code: "MS", name: "Montserrat", default_currency: "XCD", default_locale: "en-MS", calling_code: "+1664", active: true },
  { code: "MT", name: "Malta", default_currency: "EUR", default_locale: "en-MT", calling_code: "+356", active: true },
  { code: "MU", name: "Mauritius", default_currency: "MUR", default_locale: "en-MU", calling_code: "+230", active: true },
  { code: "MV", name: "Maldives", default_currency: "MVR", default_locale: "dv-MV", calling_code: "+960", active: true },
  { code: "MW", name: "Malawi", default_currency: "MWK", default_locale: "en-MW", calling_code: "+265", active: true },
  { code: "MX", name: "Mexico", default_currency: "MXN", default_locale: "es-MX", calling_code: "+52", active: true },
  { code: "MY", name: "Malaysia", default_currency: "MYR", default_locale: "ms-MY", calling_code: "+60", active: true },
  { code: "MZ", name: "Mozambique", default_currency: "MZN", default_locale: "pt-MZ", calling_code: "+258", active: true },
  { code: "NA", name: "Namibia", default_currency: "NAD", default_locale: "en-NA", calling_code: "+264", active: true },
  { code: "NC", name: "New Caledonia", default_currency: "XPF", default_locale: "fr-NC", calling_code: "+687", active: true },
  { code: "NE", name: "Niger", default_currency: "XOF", default_locale: "fr-NE", calling_code: "+227", active: true },
  { code: "NF", name: "Norfolk Island", default_currency: "AUD", default_locale: "en-NF", calling_code: "+672", active: true },
  { code: "NG", name: "Nigeria", default_currency: "NGN", default_locale: "en-NG", calling_code: "+234", active: true },
  { code: "NI", name: "Nicaragua", default_currency: "NIO", default_locale: "es-NI", calling_code: "+505", active: true },
  { code: "NL", name: "Netherlands", default_currency: "EUR", default_locale: "nl-NL", calling_code: "+31", active: true },
  { code: "NO", name: "Norway", default_currency: "NOK", default_locale: "nb-NO", calling_code: "+47", active: true },
  { code: "NP", name: "Nepal", default_currency: "NPR", default_locale: "ne-NP", calling_code: "+977", active: true },
  { code: "NR", name: "Nauru", default_currency: "AUD", default_locale: "en-NR", calling_code: "+674", active: true },
  { code: "NU", name: "Niue", default_currency: "NZD", default_locale: "en-NU", calling_code: "+683", active: true },
  { code: "NZ", name: "New Zealand", default_currency: "NZD", default_locale: "en-NZ", calling_code: "+64", active: true },
  { code: "OM", name: "Oman", default_currency: "OMR", default_locale: "ar-OM", calling_code: "+968", active: true },
  { code: "PA", name: "Panama", default_currency: "PAB", default_locale: "es-PA", calling_code: "+507", active: true },
  { code: "PE", name: "Peru", default_currency: "PEN", default_locale: "es-PE", calling_code: "+51", active: true },
  { code: "PF", name: "French Polynesia", default_currency: "XPF", default_locale: "fr-PF", calling_code: "+689", active: true },
  { code: "PG", name: "Papua New Guinea", default_currency: "PGK", default_locale: "en-PG", calling_code: "+675", active: true },
  { code: "PH", name: "Philippines", default_currency: "PHP", default_locale: "en-PH", calling_code: "+63", active: true },
  { code: "PK", name: "Pakistan", default_currency: "PKR", default_locale: "en-PK", calling_code: "+92", active: true },
  { code: "PL", name: "Poland", default_currency: "PLN", default_locale: "pl-PL", calling_code: "+48", active: true },
  { code: "PM", name: "Saint Pierre and Miquelon", default_currency: "EUR", default_locale: "fr-PM", calling_code: "+508", active: true },
  { code: "PN", name: "Pitcairn Islands", default_currency: "NZD", default_locale: "en-PN", calling_code: "+64", active: true },
  { code: "PR", name: "Puerto Rico", default_currency: "USD", default_locale: "es-PR", calling_code: "+1", active: true },
  { code: "PS", name: "Palestine", default_currency: "ILS", default_locale: "ar-PS", calling_code: "+970", active: true },
  { code: "PT", name: "Portugal", default_currency: "EUR", default_locale: "pt-PT", calling_code: "+351", active: true },
  { code: "PW", name: "Palau", default_currency: "USD", default_locale: "en-PW", calling_code: "+680", active: true },
  { code: "PY", name: "Paraguay", default_currency: "PYG", default_locale: "es-PY", calling_code: "+595", active: true },
  { code: "QA", name: "Qatar", default_currency: "QAR", default_locale: "ar-QA", calling_code: "+974", active: true },
  { code: "RE", name: "Réunion", default_currency: "EUR", default_locale: "fr-RE", calling_code: "+262", active: false },
  { code: "RO", name: "Romania", default_currency: "RON", default_locale: "ro-RO", calling_code: "+40", active: true },
  { code: "RS", name: "Serbia", default_currency: "RSD", default_locale: "sr-RS", calling_code: "+381", active: true },
  { code: "RU", name: "Russia", default_currency: "RUB", default_locale: "ru-RU", calling_code: "+7", active: true },
  { code: "RW", name: "Rwanda", default_currency: "RWF", default_locale: "en-RW", calling_code: "+250", active: true },
  { code: "SA", name: "Saudi Arabia", default_currency: "SAR", default_locale: "ar-SA", calling_code: "+966", active: true },
  { code: "SB", name: "Solomon Islands", default_currency: "SBD", default_locale: "en-SB", calling_code: "+677", active: true },
  { code: "SC", name: "Seychelles", default_currency: "SCR", default_locale: "en-SC", calling_code: "+248", active: true },
  { code: "SD", name: "Sudan", default_currency: "SDG", default_locale: "ar-SD", calling_code: "+249", active: true },
  { code: "SE", name: "Sweden", default_currency: "SEK", default_locale: "sv-SE", calling_code: "+46", active: true },
  { code: "SG", name: "Singapore", default_currency: "SGD", default_locale: "en-SG", calling_code: "+65", active: true },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", default_currency: "GBP", default_locale: "en-SH", calling_code: "+290", active: true },
  { code: "SI", name: "Slovenia", default_currency: "EUR", default_locale: "sl-SI", calling_code: "+386", active: true },
  { code: "SJ", name: "Svalbard and Jan Mayen", default_currency: "NOK", default_locale: "no-SJ", calling_code: "+47", active: true },
  { code: "SK", name: "Slovakia", default_currency: "EUR", default_locale: "sk-SK", calling_code: "+421", active: true },
  { code: "SL", name: "Sierra Leone", default_currency: "SLE", default_locale: "en-SL", calling_code: "+232", active: true },
  { code: "SM", name: "San Marino", default_currency: "EUR", default_locale: "it-SM", calling_code: "+378", active: true },
  { code: "SN", name: "Senegal", default_currency: "XOF", default_locale: "fr-SN", calling_code: "+221", active: true },
  { code: "SO", name: "Somalia", default_currency: "SOS", default_locale: "ar-SO", calling_code: "+252", active: true },
  { code: "SR", name: "Suriname", default_currency: "SRD", default_locale: "nl-SR", calling_code: "+597", active: true },
  { code: "SS", name: "South Sudan", default_currency: "SSP", default_locale: "en-SS", calling_code: "+211", active: true },
  { code: "ST", name: "São Tomé and Príncipe", default_currency: "STN", default_locale: "pt-ST", calling_code: "+239", active: false },
  { code: "SV", name: "El Salvador", default_currency: "USD", default_locale: "es-SV", calling_code: "+503", active: true },
  { code: "SX", name: "Sint Maarten", default_currency: "ANG", default_locale: "en-SX", calling_code: "+1721", active: true },
  { code: "SY", name: "Syria", default_currency: "SYP", default_locale: "ar-SY", calling_code: "+963", active: true },
  { code: "SZ", name: "Eswatini", default_currency: "SZL", default_locale: "en-SZ", calling_code: "+268", active: true },
  { code: "TC", name: "Turks and Caicos Islands", default_currency: "USD", default_locale: "en-TC", calling_code: "+1649", active: true },
  { code: "TD", name: "Chad", default_currency: "XAF", default_locale: "ar-TD", calling_code: "+235", active: true },
  { code: "TF", name: "French Southern and Antarctic Lands", default_currency: "EUR", default_locale: "fr-TF", calling_code: "+262", active: true },
  { code: "TG", name: "Togo", default_currency: "XOF", default_locale: "fr-TG", calling_code: "+228", active: true },
  { code: "TH", name: "Thailand", default_currency: "THB", default_locale: "th-TH", calling_code: "+66", active: true },
  { code: "TJ", name: "Tajikistan", default_currency: "TJS", default_locale: "tg-TJ", calling_code: "+992", active: true },
  { code: "TK", name: "Tokelau", default_currency: "NZD", default_locale: "en-TK", calling_code: "+690", active: true },
  { code: "TL", name: "Timor-Leste", default_currency: "USD", default_locale: "pt-TL", calling_code: "+670", active: true },
  { code: "TM", name: "Turkmenistan", default_currency: "TMT", default_locale: "tk-TM", calling_code: "+993", active: true },
  { code: "TN", name: "Tunisia", default_currency: "TND", default_locale: "ar-TN", calling_code: "+216", active: true },
  { code: "TO", name: "Tonga", default_currency: "TOP", default_locale: "en-TO", calling_code: "+676", active: true },
  { code: "TR", name: "Türkiye", default_currency: "TRY", default_locale: "tr-TR", calling_code: "+90", active: true },
  { code: "TT", name: "Trinidad and Tobago", default_currency: "TTD", default_locale: "en-TT", calling_code: "+1868", active: true },
  { code: "TV", name: "Tuvalu", default_currency: "AUD", default_locale: "en-TV", calling_code: "+688", active: true },
  { code: "TW", name: "Taiwan", default_currency: "TWD", default_locale: "zh-TW", calling_code: "+886", active: true },
  { code: "TZ", name: "Tanzania", default_currency: "TZS", default_locale: "sw-TZ", calling_code: "+255", active: true },
  { code: "UA", name: "Ukraine", default_currency: "UAH", default_locale: "uk-UA", calling_code: "+380", active: true },
  { code: "UG", name: "Uganda", default_currency: "UGX", default_locale: "en-UG", calling_code: "+256", active: true },
  { code: "UM", name: "United States Minor Outlying Islands", default_currency: "USD", default_locale: "en-UM", calling_code: "+268", active: false },
  { code: "US", name: "United States", default_currency: "USD", default_locale: "en-US", calling_code: "+1", active: true },
  { code: "UY", name: "Uruguay", default_currency: "UYU", default_locale: "es-UY", calling_code: "+598", active: true },
  { code: "UZ", name: "Uzbekistan", default_currency: "UZS", default_locale: "uz-UZ", calling_code: "+998", active: true },
  { code: "VA", name: "Vatican City", default_currency: "EUR", default_locale: "it-VA", calling_code: "+39", active: true },
  { code: "VC", name: "Saint Vincent and the Grenadines", default_currency: "XCD", default_locale: "en-VC", calling_code: "+1784", active: true },
  { code: "VE", name: "Venezuela", default_currency: "VES", default_locale: "es-VE", calling_code: "+58", active: true },
  { code: "VG", name: "British Virgin Islands", default_currency: "USD", default_locale: "en-VG", calling_code: "+1284", active: true },
  { code: "VI", name: "United States Virgin Islands", default_currency: "USD", default_locale: "en-VI", calling_code: "+1340", active: true },
  { code: "VN", name: "Vietnam", default_currency: "VND", default_locale: "vi-VN", calling_code: "+84", active: true },
  { code: "VU", name: "Vanuatu", default_currency: "VUV", default_locale: "bi-VU", calling_code: "+678", active: true },
  { code: "WF", name: "Wallis and Futuna", default_currency: "XPF", default_locale: "fr-WF", calling_code: "+681", active: true },
  { code: "WS", name: "Samoa", default_currency: "WST", default_locale: "en-WS", calling_code: "+685", active: true },
  { code: "XK", name: "Kosovo", default_currency: "EUR", default_locale: "sq-XK", calling_code: "+383", active: true },
  { code: "YE", name: "Yemen", default_currency: "YER", default_locale: "ar-YE", calling_code: "+967", active: true },
  { code: "YT", name: "Mayotte", default_currency: "EUR", default_locale: "fr-YT", calling_code: "+262", active: true },
  { code: "ZA", name: "South Africa", default_currency: "ZAR", default_locale: "en-ZA", calling_code: "+27", active: true },
  { code: "ZM", name: "Zambia", default_currency: "ZMW", default_locale: "en-ZM", calling_code: "+260", active: true },
  { code: "ZW", name: "Zimbabwe", default_currency: "USD", default_locale: "en-ZW", calling_code: "+263", active: true },
];
